config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "users#index"
  resources :users do
    resource :profile
  end

  resources :books do
    resources :feeds
  end

  resources :schedules

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    ## user ||= User.new
    can :manage, Book, creator: user.id
    can :manage, Feed do |feed|
      feed.book.creator==user.id
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :feeds, dependent: :destroy
  has_and_belongs_to_many :users, join_table: :schedules
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  belongs_to :book
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  has_and_belongs_to_many :books, join_table: :schedules

  before_create :build_default_profile

  private

  def build_default_profile
    build_profile
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource

  def index
    @books = Book.where(creator: current_user)
    render :index
  end


  def show
    @book = Book.find(params['id'])
    @feeds = @book.feeds
    render :show
  end

  def edit


  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def show
    id = params[:id]
    @feed = Feed.find(id)
    render :show
  end

  def index
    @feeds = Feed.all
    render :index
  end

  def edit
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @profile = current_user.profile
    render :edit
  end

  def update
    @profile = Profile.find_by_user_id(params['user_id'])
    @profile.update(profile_params)
    render :edit
  end

  private
  def profile_params
    params.require(:profile).permit(
        :send_to_email
    )
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    @schedules = Schedule.where(user_id: current_user)
    render :index
  end

  def show
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    render :index
  end

  def show
    id = params[:id]
    @user = User.find(id)
    @profile = User.find(id).profile
    render :show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/books/index.html.haml
%table
  %thead
    %tr
      - Book.column_names.each do |c|
        %th= c
      %th= 'operation'
  %tbody
    - @books.each do |book|
      %tr
        - book.slice(*Book.column_names).values.each do |v|
          %td= v
        %td
          = link_to 'Details', book_path(book), class: :button
          = link_to 'Drop', '#', class: :button

-#= link_to 'Add New Book', '#', class: :button
%a{'data-open' => 'new_book'}= 'Add New Book'

app/views/books/show.html.haml
%table
  %thead
    %tr
      - Feed.column_names.each do |c|
        %th= c
      %th= 'operation'
  %tbody
    - @feeds.each do |feed|
      %tr
        - feed.slice(*Feed.column_names).values.each do |v|
          %td= v
        %td
          = link_to 'edit', '#', class: :button
          = link_to 'drop', '#', class: :button

= link_to 'Add New Feed', '#', class: :button

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tag

  %body
    = render 'shared/top_bar'

    = yield

app/views/profiles/edit.html.haml
= simple_form_for @profile, url: user_profile_path do |f|
  = f.input :send_to_email
  = f.submit class: :button

app/views/schedules/index.html.haml
%table
  %thead
    %tr
      - Schedule.column_names.each do |c|
        %th= c
      %th= 'operation'
  %tbody
    - @schedules.each do |s|
      %tr
        - s.slice(*Schedule.column_names).values.each do |v|
          %td= v
        %td
          = link_to 'edit', '#', class: :button
          = link_to 'drop', '#', class: :button

= link_to 'Add New Schedule', '#', class: :button

app/views/shared/_dialog.html.haml
.reveal{'aria-hidden' => 'true', 'aria-labelledby' => 'modalTitle', 'data-reveal' => '', :id => modal[:id], :role => 'dialog'}
  #content
  %button.close-button{'aria-label' => 'Close modal', 'data-close' => '', :type => 'button'}
    %span{'aria-hidden' => 'true'} ×

app/views/shared/_notification.html.haml
- if notice
  .success.callout.notification{'data-closable' => ''}
    %p= notice
    %button.close-button{'aria-label' => 'Dismiss alert', 'data-close' => '', :type => 'button'}
      %span{'aria-hidden' => 'true'} ×

- if alert
  .alert.callout.notification{'data-closable' => ''}
    %p= alert
    %button.close-button{'aria-label' => 'Dismiss alert', 'data-close' => '', :type => 'button'}
      %span{'aria-hidden' => 'true'} ×

app/views/shared/_table.html.haml
- icon_map ={delete: 'fi-x', show: 'fi-magnifying-glass', complement: 'fi-pencil',
             edit: 'fi-pencil', add_adjuvant: 'fi-plus', add_followup: 'fi-plus'}
%table
  %thead
    %tr
      - columns.each do |column|
        %th
          = sort_link column, collection

      %th{ colspan: operations.size}= vt 'operations'

  %tbody
    - collection.each do |row|
      %tr
        - columns.each do |column|
          - val = row.send column
          - case val
            - when Time, Date
              %td= l val, format: :long
            - when ::Enumerize::Value
              %td= val.text
            - else
              %td= val

        - operations.each do |key, value|
          %td
            - if url_method[key].is_a? Proc
              = url_method[key].call row
            - else
              %a{:href => send(url_method[key], row), class: icon_map[key], :data => value }
                = vt key

app/views/shared/_top_bar.html.haml
.top-bar
  .top-bar-title
    %span{'data-hide-for' => 'medium', 'data-responsive-toggle' => 'responsive-menu'}
      %span.menu-icon.dark{'data-toggle' => ''}

  #responsive-menu
    .top-bar-left
      - if user_signed_in?
        %ul.dropdown.menu{'data-dropdown-menu' => ''}
          %li
            - model_name = User.model_name.human
            = link_to model_name, users_path

          %li
            - model_name = Book.model_name.human
            = link_to model_name, books_path

          %li
            - model_name = Schedule.model_name.human
            = link_to model_name, schedules_path

    .top-bar-right
      %ul.dropdown.menu{'data-dropdown-menu' => ''}
        - if user_signed_in?
          %li
            %a= "#{current_user.email}"
            %ul.menu.vertical
              %li
                = link_to :edit_profile, edit_user_profile_path(user_id: current_user.id)
          %li.divider
          %li
            = link_to :sign_out, destroy_user_session_path, method: :delete, class: :button
        - else
          %li
            = link_to :sign_in, new_user_session_path, class: :button

app/views/shared/_wf_error.html.haml
.alert.callout
  %p
    %i.fi-alert
    = @err_msg

app/views/users/index.haml
%div.userlist
  %table{border: 1}
    %thead
      %tr
      - User.column_names.each do |c|
        %td= c
    %tbody
      - @users.each do |row|
        %tr
          - row.attributes.values.each do |column|
            %td= column

app/views/users/show.haml
%p= current_user.attributes.values
%p= @profile.attributes.values